 import { Detail } from "./detail";

 export const DETAIL: Detail =
 {
    "name": "Pablo Picasso",
    "birthday": "1881",
    "deathday": "1973",
    "nationality": "Spanish",
    "biography": "Born in Málaga, Spain, in 1881, Pablo Picasso showed an early passion for drawing. His father, an art teacher, began giving him lessons in figure drawing and oil painting at the age of seven. Picasso enrolled in the School of Fine Arts in Barcelona and then at Madrid, but withdrew from formal training in 1899 to return to Barcelona, where he worked as a graphic artist. In 1900, Picasso made his first visit to Paris, and until 1904, he split his time between Paris and Barcelona.\n\nLate in 1901, Picasso began making paintings on themes of desolation and despair, depicting solitary and melancholy figures in paintings flooded with blue. In 1904, Picasso began his Rose Period, lightening his palette from the dark, moody blues of the previous years in favor of beige, red, and rose tones. Casting aside the melancholy subjects of the Blue Period, Picasso painted circus perform- ers, harlequins, and clowns.\n\nAfter meeting Georges Braque in 1907, Picasso and Braque worked closely together to develop Cubism. By 1910, they had developed a distinctive Cubist idiom, fracturing their subjects into small, faceted forms and working with a muted palette. Rejecting the traditional depiction of three-dimensional objects from one viewpoint, they instead represented the subject from a multitude of perspectives. In 1912, Picasso and Braque began experimenting with collage and papier collé, introducing real elements, such as newsprint, artificial wood, and wallpaper, into their paintings to achieve trompe-l’oeil effects. By 1911–12, Cub- ism had become popular as the latest avant-garde movement and progressive painters across Europe began painting in Cubist styles.\n\nAfter the upheaval of World War One, Picasso - together with other European artists including André Derain, Giorgio de Chirico, and Fernand Léger - returned to a more traditional artistichis exploration of Cubism, often painting works in remarkably different styles in a period of only a few hours.\nBy 1927, Picasso began experimenting with Surrealist imagery, incorporating morphed and distorted figures in his paintings. When the Spanish Civil War broke out in 1936, Picasso reacted with explicit, emotional works, painting the masterpiece Guernica in response to the bombing of the town by the fascist Generalissimo Francisco Franco in 1937.\n\nFrom the late 1940s through the 1960s, Picasso worked primarily in the south of France, where he painted, made ceramics, and experimented with printmaking. In the 1950s, Picasso began reinterpreting the work of the great masters, making paintings based on Velázquez, Goya, Manet, Courbet, and Delacroix. During the 1950s, Picasso’s international fame increased greatly with large exhibitions and retrospectives across the world. He continued to work prolifically through his eighties and nineties. He died in 1973, leaving behind an unparalleled legacy that has shaped the development of modern and contemporary art."
  }